fix versioning, publishin pipeline, config

diff --git a/.github/workflows/python-publish.yml b/.github/workflows/python-publish.yml
--- a/.github/workflows/python-publish.yml
+++ b/.github/workflows/python-publish.yml
@@ -1,10 +1,11 @@
-# This workflow will upload a Python Package using Twine when a release is created
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
-
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
+# Publish individual packages to PyPI when a release is created.
+#
+# Release tag conventions:
+#   netflixext/vX.Y.Z  - publishes metaflow-netflixext
+#   functions/vX.Y.Z   - publishes metaflow-functions
+#
+# The workflow parses the tag to determine which package to build and publish.
+# Only the package matching the tag prefix is published.
 
 name: Publish
 
@@ -17,36 +18,45 @@ permissions:
 
 jobs:
   deploy:
-
     runs-on: ubuntu-latest
-    # Specifying a GitHub environment is optional, but strongly encouraged
     environment: pypi
     permissions:
-      # IMPORTANT: this permission is mandatory for Trusted Publishing
       id-token: write
+
     steps:
-    - uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+
+    - name: Determine which package to publish
+      id: detect
+      run: |
+        TAG="${{ github.event.release.tag_name }}"
+        echo "Release tag: $TAG"
+
+        if [[ "$TAG" == netflixext/* ]]; then
+          echo "package=metaflow-netflixext" >> $GITHUB_OUTPUT
+        elif [[ "$TAG" == functions/* ]]; then
+          echo "package=metaflow-functions" >> $GITHUB_OUTPUT
+        else
+          echo "::error::Unknown release tag format '$TAG'. Use 'netflixext/vX.Y.Z' or 'functions/vX.Y.Z'."
+          exit 1
+        fi
+
     - name: Set up Python
-      uses: actions/setup-python@v3
+      uses: actions/setup-python@v5
       with:
         python-version: '3.x'
-    - name: Install dependencies
+
+    - name: Install build dependencies
       run: |
         python -m pip install --upgrade pip
         pip install setuptools wheel twine
-    - name: Build packages
+
+    - name: Build package
       run: |
-        for pkg in metaflow-functions; do
-          echo "Building $pkg..."
-          cd $pkg
-          python setup.py sdist bdist_wheel --universal
-          cd ..
-        done
-    #- name: Publish metaflow-netflixext
-    #  uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # 1.13.0
-    #  with:
-    #    packages-dir: metaflow-netflixext/dist/
-    - name: Publish metaflow-functions
+        cd ${{ steps.detect.outputs.package }}
+        python setup.py sdist bdist_wheel --universal
+
+    - name: Publish to PyPI
       uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e # 1.13.0
       with:
-        packages-dir: metaflow-functions/dist/
+        packages-dir: ${{ steps.detect.outputs.package }}/dist/
